name = "edwinfoxbarberstyle-web"
main = "worker.js"
compatibility_date = "2026-07-27"

[assets]
directory = "./"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
serve_directly = true

[[r2_buckets]]
binding = "EDWIN_ASSETS"
bucket_name = "edwin-assets"

[[r2_buckets]]
binding = "EDWIN_MEDIA"
bucket_name = "edwin-media"

[[r2_buckets]]
binding = "EDWIN_DATA"
bucket_name = "edwin-data"
